// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Titile      string  `json:"titile"`
	Description string  `json:"description"`
	Company     string  `json:"company"`
	URL         *string `json:"url,omitempty"`
}

type DeleteJobResponse struct {
	DeleteJobID string `json:"deleteJobId"`
}

type JobListing struct {
	ID          string `json:"_id"`
	Titile      string `json:"titile"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateJobListingInput struct {
	Titile      *string `json:"titile,omitempty"`
	Description *string `json:"description,omitempty"`
	Company     *string `json:"company,omitempty"`
	URL         *string `json:"url,omitempty"`
}
